import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StorProvider from "./libs/useStore";
import {Provider} from "@/app/provider" 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  types: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <StorProvider>
          <body className={inter.className}>{children}</body>
        </StorProvider>
      </Provider>
    </html>
  );
}
